---
title: "Dolphins 2"
---

```{mermaid}

```mermaid
graph TD;
    classDef green fill:#90EE90,stroke:#008000;
    classDef red fill:#FF6347,stroke:#8B0000;
    
    1["Length=3 & Gills=no & Beak=yes & Teeth=many"]:::green;
    2["Length=4 & Gills=no & Beak=yes & Teeth=many"]:::green;
    3["Length=3 & Gills=no & Beak=yes & Teeth=few"]:::green;
    4["Length=5 & Gills=yes & Beak=yes & Teeth=many"]:::red;
    5["Gills=no & Beak=yes & Teeth=many"];
    6["Length=3 & Beak=yes & Teeth=many"];
    7["Length=3 & Gills=no & Teeth=many"];
    8["Length=3 & Gills=no & Beak=yes"];
    9["Beak=yes & Teeth=many"];
    10["Gills=no & Teeth=many"];
    11["Gills=no & Beak=yes"]:::green;
    12["Teeth=many"];
    13["Beak=yes"]:::green;
    14["true"]:::green;
    15["Gills=no"]:::green;
    16["Length=3 & Teeth=many"];
    17["Length=3 & Beak=yes"];
    18["Length=3"];
    19["Length=3 & Gills=no"];
    20["Length=4 & Beak=yes & Teeth=many"];
    21["Length=4 & Gills=no & Teeth=many"];
    22["Length=4 & Gills=no & Beak=yes"];
    23["Length=4 & Teeth=many"];
    24["Length=4 & Beak=yes"];
    25["Length=4"];
    26["Length=4 & Gills=no"];
    27["Gills=no & Beak=yes & Teeth=few"];
    28["Length=3 & Beak=yes & Teeth=few"];
    29["Length=3 & Gills=no & Teeth=few"];
    30["Beak=yes & Teeth=few"];
    31["Gills=no & Teeth=few"];
    32["Teeth=few"];
    33["Length=3 & Teeth=few"];
    34["Gills=yes & Beak=yes & Teeth=many"];
    35["Length=5 & Beak=yes & Teeth=many"];
    36["Length=5 & Gills=yes & Teeth=many"];
    37["Length=5 & Gills=yes & Beak=yes"];
    38["Gills=yes & Teeth=many"];
    39["Gills=yes & Beak=yes"];
    40["Gills=yes"];
    41["Length=5 & Teeth=many"];
    42["Length=5 & Beak=yes"];
    43["Length=5"];
    44["Length=5 & Gills=yes"];
    
    5 --> 1;
    6 --> 1;
    7 --> 1;
    8 --> 1;
    9 --> 5;
    10 --> 5;
    11 --> 5;
    12 --> 9;
    13 --> 9;
    14 --> 12;
    14 --> 13;
    12 --> 10;
    15 --> 10;
    14 --> 15;
    13 --> 11;
    15 --> 11;
    9 --> 6;
    16 --> 6;
    17 --> 6;
    12 --> 16;
    18 --> 16;
    14 --> 18;
    13 --> 17;
    18 --> 17;
    10 --> 7;
    16 --> 7;
    19 --> 7;
    15 --> 19;
    18 --> 19;
    11 --> 8;
    17 --> 8;
    19 --> 8;
    5 --> 2;
    20 --> 2;
    21 --> 2;
    22 --> 2;
    9 --> 20;
    23 --> 20;
    24 --> 20;
    12 --> 23;
    25 --> 23;
    14 --> 25;
    13 --> 24;
    25 --> 24;
    10 --> 21;
    23 --> 21;
    26 --> 21;
    15 --> 26;
    25 --> 26;
    11 --> 22;
    24 --> 22;
    26 --> 22;
    27 --> 3;
    28 --> 3;
    29 --> 3;
    8 --> 3;
    30 --> 27;
    31 --> 27;
    11 --> 27;
    32 --> 30;
    13 --> 30;
    14 --> 32;
    32 --> 31;
    15 --> 31;
    30 --> 28;
    33 --> 28;
    17 --> 28;
    32 --> 33;
    18 --> 33;
    31 --> 29;
    33 --> 29;
    19 --> 29;
    34 --> 4;
    35 --> 4;
    36 --> 4;
    37 --> 4;
    9 --> 34;
    38 --> 34;
    39 --> 34;
    12 --> 38;
    40 --> 38;
    14 --> 40;
    13 --> 39;
    40 --> 39;
    9 --> 35;
    41 --> 35;
    42 --> 35;
    12 --> 41;
    43 --> 41;
    14 --> 43;
    13 --> 42;
    43 --> 42;
    38 --> 36;
    41 --> 36;
    44 --> 36;
    40 --> 44;
    43 --> 44;
    39 --> 37;
    42 --> 37;
    44 --> 37;
```


```
