project:
  type: website

website:
  title: "MLbook Figures"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/flach/mlbook-figs
    contents:
      - href: index.qmd
        text: Home
      - href: chapter_1.qmd
        text: Chapter 1
      - href: chapter_2.qmd
        text: Chapter 2
      - href: chapter_3.qmd
        text: Chapter 3
      - href: chapter_4.qmd
        text: Chapter 4
      - href: chapter_5.qmd
        text: Chapter 5
      - href: chapter_6.qmd
        text: Chapter 6
      - href: chapter_7.qmd
        text: Chapter 7
      - href: chapter_8.qmd
        text: Chapter 8
      - href: chapter_9.qmd
        text: Chapter 9
      - href: chapter_10.qmd
        text: Chapter 10
      - href: chapter_11.qmd
        text: Chapter 11
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



